### ISSUE TITLE
Add some useful information in README

### ISSUE THREAD

**Issue by lc3t35** [rdagger/faneron#1]
You will need a AWSAccessKeyId and AWSSecretAccessKey in Meteor.settings and a bucket with the following CORS configuration (https://github.com/CulturalMe/meteor-slingshot#aws-s3)
otherwise you have a nice error : 

> Error: Match error: Missing key 'AWSAccessKeyId'
> at exports.check (packages/check/match.js:34:1)
> at new Slingshot.Directive (packages/edgee_slingshot/packages/edgee_slingshot.js:304:1)

**Comment by rdagger** [comment]
I updated the readme.  Thanks for the helpful feedback.

**Comment by lc3t35** [comment]
Perfect, thx
